global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 24h
  receiver: 'email'
receivers:
  - name: 'email'
    email_configs:
      - to: '**********@gmail.com'
        from: '*******@yandex.ru'
        smarthost: smtp.yandex.ru:587
        auth_username: '*******@yandex.ru'
        auth_identity: '*******'
        auth_password: '*****************'